@startuml package
allow_mixing

package "Smart Home System"{
    package "Control Unit" as cu{
        Interface "Imports" as i{
            I Lights
            I AC
            I Appliances
            I Food API
            I Security
        }
        component "Command Control"
        component "Timer"
    }

    package "Lights" as l{
        component "Lights Control"
    }

    package "AC" as ac{
        component "AC Control"
    }

    package "Appliances" as ap{
        component "Smart fridge control"
        component "Brewer control"
    }

    package "Food API" as f{
        component "Order food"
    }

    package "Security" as s{
        component "Police Call"
        component "Door Control"
        component "Alarm"
    }

    package "Sensors" as se{
        component "Temperature"
        component "Movement"
    }

    package "Phone" as ph {
        component "Location"
        component "Commands"
    }
}

i <.. l : imports
i <.. ac : imports
i <.. ap : imports
i <.. f : imports
i <.. s : imports
i <.. se : imports
i <.. ph : imports
@enduml